# Generated by Django 4.2.23 on 2025-09-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_company_alter_alljob_company_alter_job_company_and_more'),
    ]

    operations = [
    ]
