# Generated by Django 4.2.23 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20250908_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alljob',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job1',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job2',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job3',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
