# Generated by Django 4.2.23 on 2025-09-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_company_alter_alljob_company_alter_job_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alljob',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='job1',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='job2',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='job3',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
