# Generated by Django 4.2.23 on 2025-09-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_alljob_company_alter_job_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
